# Generated by Django 2.2 on 2019-04-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeAvailability',
            fields=[
                ('index_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.TextField()),
                ('number', models.FloatField()),
                ('name', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('bike_stands', models.FloatField()),
                ('available_bike_stands', models.FloatField()),
                ('available_bikes', models.FloatField()),
            ],
            options={
                'db_table': 'bike_availability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('index_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.TextField()),
                ('name', models.TextField()),
                ('address_1', models.TextField()),
                ('time', models.TextField()),
                ('duration', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('yes_rsvp_count', models.FloatField()),
                ('maybe_rsvp_count', models.FloatField()),
            ],
            options={
                'db_table': 'event_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PollutionLevel',
            fields=[
                ('index_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.TextField()),
                ('number', models.FloatField()),
                ('aqi', models.FloatField()),
                ('dominant_pollutant', models.TextField()),
                ('co', models.FloatField()),
                ('no2', models.FloatField()),
                ('o3', models.FloatField()),
                ('so2', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pm25', models.FloatField()),
            ],
            options={
                'db_table': 'pollution_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrafficInfo',
            fields=[
                ('index_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.TextField()),
                ('number', models.FloatField()),
                ('distance', models.FloatField()),
                ('duration', models.FloatField()),
            ],
            options={
                'db_table': 'traffic_info',
                'managed': False,
            },
        ),
    ]
